defaults:
  - dataloader : dataloader
  - optimizer  : Adam
  - model      : vae

epoch        : 5
loss_function: cross_entropy
# loss_function: vae_loss_function

logging_params:
  save_dir: "logs/"
  name    : "VAE"